# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: NEBRİNİN OĞLU
author: SELAMİ IŞIK
logo: logo.jpeg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ogun/nebrinin-oglu # Online location of your book
  branch: master # Which branch of the repository should be used when creating links (optional)
